const QUESTIONS_MODE_1 = 10;
const QUESTIONS_MODE_2 = 20;
const QUESTIONS_MODE_3 = 30;
const DRAW_POINTS_MODE_1 = 5;
const DRAW_POINTS_MODE_2 = 10;
const DRAW_POINTS_MODE_3 = 15;
const LOSE_POINTS_MODE_1 = -2;
const LOSE_POINTS_MODE_2 = -4;
const LOSE_POINTS_MODE_3 = -6;

export default {
  QUESTIONS_MODE_1,
  QUESTIONS_MODE_2,
  QUESTIONS_MODE_3,
  DRAW_POINTS_MODE_1,
  DRAW_POINTS_MODE_2,
  DRAW_POINTS_MODE_3,
  LOSE_POINTS_MODE_1,
  LOSE_POINTS_MODE_2,
  LOSE_POINTS_MODE_3,
};
